# Generated by Django 2.1.15 on 2020-06-11 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_genre_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
