# Generated by Django 2.1.15 on 2020-06-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200612_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='movie_title',
            field=models.CharField(max_length=100),
        ),
    ]
