# Generated by Django 2.1.15 on 2020-06-16 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_today'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='today',
        ),
    ]
